version: '3'
services:
  postgres-db:
    image: "postgres:16"
    container_name: "store"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - '5432:5432'
